### ISSUE TITLE
../../src/riscv-pk/configure file not found

### ISSUE THREAD

**Issue by P3nt1um** [oscomp/testsuits-for-oskernel#1]
At the end of `make` process after adding riscv path, it shows
`../../src/riscv-pk/configure file not found`, 
after adding the `src` directory of busybear to appropirate directory, it works. 
Does not it generate itself?
[https://github.com/michaeljclark/busybear-linux](url)

**Comment by elliott10** [comment]
Thanks for feedback

We have added module riscv-pk
