### ISSUE TITLE
请问大赛官方可以公布LoongArch testcases的源码吗？

### ISSUE THREAD

**Issue by Fediory** [oscomp/testsuits-for-oskernel#16]

**Comment by w-mj** [comment]
在赛题描述页面有Loong Arch testcase的仓库地址。

**Comment by Fediory** [comment]
Loong Arch：https://github.com/oscomp/testsuits-for-oskernel/tree/pre-2024
请问是这个链接吗，我点进去后发现LA的镜像和部分测例源码是不对应的，比如mmap。

**Comment by w-mj** [comment]
不好意思题目中链接有误，正确的地址应该是：https://github.com/LoongsonLab/oscomp-testsuits-loongarch
