### ISSUE TITLE
Duplicated SYSCALL number

### ISSUE THREAD

**Issue by willson0v0** [oscomp/testsuits-for-oskernel#2]
In testsuits-for-oskernel/oscomp_syscalls.md, SYS_pipe2 and SYS_execve both use 59 as its SYSCALL number.
Just for reference, in the syscall call table of Linux under x86-64, the call number of SYS_exceve is 59 and the call number of SYS_pipe2 is 293.

**Comment by elliott10** [comment]
Thank you for your feedback !
We have corrected it.
<br>
In Linux, syscalls ID of various CPU architectures are different.
