### ISSUE TITLE
SD卡里面的文件

### ISSUE THREAD

**Issue by sunshine-lcc** [oscomp/testsuits-for-oskernel#9]
请问下你们能提供下评测SD卡的img文件吗？对于SD卡里面的文件内容不是很清楚

**Comment by w-mj** [comment]
目前SD卡中的文件列表为：
file:busybox
file:busybox_cmd.txt
file:busybox_testcode.sh

file:date.lua
file:file_io.lua
file:lua
file:lua_testcode.sh
file:max_min.lua
file:random.lua
file:remove.lua
file:round_num.lua
file:sin30.lua
file:sort.lua
file:strings.lua
file:test.sh

file:lmbench_all
